# Generated by Django 4.2.3 on 2023-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('versity', models.TextField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('admission_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
